# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

variables:
  deploymentname: "AppService-Deploy-$(build.buildid)"
  templatefile: "modules/appService/appService.bicep"
  templateparameterfile: "modules/appService/main.parameters.json"


steps:
- task: AzurePowerShell@5
  displayName: 'App Serivice Bicep Deployment'
  inputs:
    azureSubscription: '$(serviceConnection)'
    azurePowerShellVersion: LatestVersion
    ScriptType: InlineScript
    Inline: |
      New-AzResourceGroupDeployment `
      -name "$(deploymentname)" `
      -Templatefile "$(templatefile)" `
      -TemplateParameterFile "$(templateparameterfile)" `
      -ResourceGroupName "$(resourceGroupName)" `
      -verbose
