trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  deploymentname: "StorageAcct-Deploy-$(build.buildid)"
  templatefile: "modules/storageAccount/storageAccount.bicep"


parameters:
- name: environmentType
  displayName: Storage Account Non-Prod or Prod
  values:
    - 'prod'
    - 'nonprod'


steps:
- task: AzurePowerShell@5
  displayName: 'Storage Account Bicep Deployment'
  inputs:
    azureSubscription: '$(serviceConnection)'
    azurePowerShellVersion: LatestVersion
    ScriptType: InlineScript
    Inline: |
      New-AzResourceGroupDeployment `
      -name "$(deploymentname)" `
      -Templatefile: "$(templatefile)" `
      -ResourceGroupName: "$(resourceGroupName)" `
      -verbose

